# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            David Riordan
tagline:          'Words on the internet.'
description:      'David Riordan writes. Sometimes.'
url:              http://daveriordan.com
baseurl:          /

author:
  name:           'David Riordan'
  url:            https://twitter.com/riordan

paginate:         10

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/riordan/blog
